site_name: REQUISITOS — Brainly
pages:
  - PRÉ-RASTREABILIDADE:
    - Argumentação: argumentacao.md
    - RichPicture: rich_picture.md
  - RASTREABILIDADE-PRINTS:
    - Versões da argumentação: argumentacao_versoes.md
    - Versões de Rich Picture: rich_picture_versoes.md
    - Confirmação do tema: confirmacao_tema.md
    - Não ao Twich.TV: nao_twich.md
    - Votação para escolha do tema: votacao_tema.md
    - Votação sistema de mensagem: votacao_mensagem.md
  - ELICITAÇÃO:
    - Plano de elicitação: plano_elicitacao.md
    - Análise de Protocolo: analise_protocolo.md
    - Brainstorming: brainstorm.md
    - Entrevista: entrevista.md
    - Introspecção: introspeccao.md
    - Observação: observacao.md
    - Storytelling: storytelling.md
    - Questionário: questionario.md
    - Priorização: priorizacao.md
  - MODELAGEM:
    - Cenários: cenarios10x5f8c4.md
    - Léxicos: lexicos10x5f8c4.md
    - Casos de Uso: 
        Perguntas e Respostas: casos_uso_perguntas_respostas.md
        Gamificação: casos_uso_gamificacao.md
        Cadastro: casos_uso_cadastro.md
        Deletar Conta: casos_uso_deletar_conta.md
        Editar perfil: casos_uso_editar_perfil.md
    - Versões antigas:
      - Versão 1:
        - Cenário: modelagem_v1/cenarios10x58ed251.md
        - Léxico: modelagem_v1/lexicos10x58ed251.md


theme:
  language: 'pt'
  name: 'material'
  logo: 'images/brainly/icon.png'
  favicon: 'images/brainly/icon.png'
  palette:
    primary: 'light blue'
    accent: 'white'

repo_name: 'Brainly'
repo_url: 'https://github.com/WelisonR/2019.1-Requisitos-Brainly'