site_name: REQUISITOS — Brainly
pages:
  - PRÉ-RASTREABILIDADE:
    - Argumentação: argumentacao.md
    - RichPicture: rich_picture.md
    - Versões antigas:
      - RichPicture: pre_rastreabilidade_v1/rich_picture_versoes.md
      - Argumentação: pre_rastreabilidade_v1/argumentacao_versoes.md
  - ELICITAÇÃO:
    - Plano de elicitação: plano_elicitacao.md
    - Análise de Protocolo: analise_protocolo.md
    - Brainstorming: brainstorm.md
    - Entrevista: entrevista.md
    - Introspecção: introspeccao.md
    - Observação: observacao.md
    - Storytelling: storytelling.md
    - Questionário: questionario.md
    - Priorização: priorizacao.md
    - Versões antigas:
        - Introspecção: elicitacao_v1/introspeccao.md
  - MODELAGEM:
    - Cenários: cenarios10x5f8c4.md
    - Léxicos: lexicos10x5f8c4.md
    - Casos de Uso: 
        Perguntas e Respostas: casos_uso_perguntas_respostas.md
        Gamificação: casos_uso_gamificacao.md
        Cadastro: casos_uso_cadastro.md
        Deletar Conta: casos_uso_deletar_conta.md
        Editar perfil: casos_uso_alterar_perfil.md
    - Especificação Suplementar: especificacao_suplementar.md
    - Backlog:
      - Backlog de Produto: backlog.md
      - Sprint Backlog: sprint_backlog.md
    - NFR: nfr.md
    - I*: i_star.md
    - Versões antigas:
        - Cenário: modelagem_v1/cenarios10x58ed251.md
        - Léxico: modelagem_v1/lexicos10x58ed251.md
        - Backlog:
          - Backlog de Produto: modelagem_v1/backlog.md
          - Sprint Backlog: modelagem_v1/sprint_backlog.md
        - Caso de Uso:
          -  Perguntas e Respostas: modelagem_v1/casos_uso/casos_uso_perguntas_respostas.md
          -  Cadastro: modelagem_v1/casos_uso/casos_uso_cadastro.md
          -  Cadastro: modelagem_v1/casos_uso/casos_uso_deletar_conta.md
          -  Gamificação: modelagem_v1/casos_uso/casos_uso_gamificacao.md       
          -  Editar perfil: modelagem_v1/casos_uso/casos_uso_alterar_perfil.md   
  - ANÁLISE:
    - Pré-Rastreabilidade: analisepre.md
    - Casos de uso: analise_casos_de_uso.md
    - iStar: analise_istar.md
  - PÓS-RASTREABILIDADE:
    - Forward-From: forward.md
    - Backward-From: backward.md
  - RASTREABILIDADE-PRINTS:
    - Confirmação do tema: rastreabilidade_prints/confirmacao_tema.md
    - Não ao Twich.TV: rastreabilidade_prints/nao_twich.md
    - Votação para escolha do tema: rastreabilidade_prints/votacao_tema.md
    - Votação sistema de mensagem: rastreabilidade_prints/votacao_mensagem.md
  - SCRIPTS: scripts.md

theme:
  language: 'pt'
  name: 'material'
  logo: 'images/brainly/icon.png'
  favicon: 'images/brainly/icon.png'
  palette:
    primary: 'light blue'
    accent: 'white'


extra_css:
  - style/extra.css

repo_name: 'Brainly'
repo_url: 'https://github.com/WelisonR/2019.1-Requisitos-Brainly'